### ISSUE TITLE
[meta] Loading animation broken in Firefox 32+

### ISSUE THREAD

**Issue by Infocatcher** [Infocatcher/Custom_Buttons#27]
Affected:
- <a href="https://github.com/Infocatcher/Custom_Buttons/tree/master/Check_for_Addons_Updates">Check for Addons Updates</a>
- <a href="https://github.com/Infocatcher/Custom_Buttons/tree/master/Extensions_Developer_Tools">Extensions Developer Tools</a>
- <a href="https://github.com/Infocatcher/Custom_Buttons/tree/master/Extensions_Installer">Extensions Installer</a>

We use
chrome://browser/skin/tabbrowser/connecting.png
chrome://browser/skin/tabbrowser/loading.png
that aren't animated anymore, see chrome://browser/skin/browser.css

``` css
@keyframes throbber-loading {
  to {
    transform: rotate(360deg);
  }
}

@keyframes throbber-connecting {
  from {
    transform: rotate(360deg);
  }
}

.tab-throbber[busy] {
  list-style-image: url("chrome://browser/skin/tabbrowser/connecting.png");
  animation-duration: 960ms;
  animation-iteration-count: infinite;
  animation-name: throbber-connecting;
  animation-timing-function: linear;
}

.tab-throbber[progress] {
  list-style-image: url("chrome://browser/skin/tabbrowser/loading.png");
  animation-duration: 800ms;
  animation-name: throbber-loading;
}
```

Or we can use alternative: chrome://global/skin/icons/loading_16.png
